spring:
  application:
    name: gitHubActionTest

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa

  h2:
    console:
      enable:true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html