name: work-1
on:
  push:
    branched:
      - main
jobs:
  hello1:
    runs-on: ubuntu-latest
    steps:
      -name: sayHello
        run: echo "Hi" 
      -name: sayMyName
        run: echo "${{ github.actor }}"
